import React from 'react';
import {
    View,
    Text,
    ScrollView,
    StyleSheet,
    Image,
    TouchableOpacity,
    ActivityIndicator,
    Alert,
} from 'react-native';
import * as Print from 'expo-print';
import * as Sharing from 'expo-sharing';
import { Ionicons } from '@expo/vector-icons';
import { Animated } from 'react-native';
import { COLORS, SIZES, SHADOWS } from '../constants/theme';
import { Car } from '../constants/cars';

export default function ComparisonScreen({ navigation, route }: { navigation: any; route: any }) {
    const cars: Car[] = route?.params?.cars || [
    ""]
    const comparisonData = [
        { label: 'Model', key: 'model' },
        { label: 'Year', key: 'year' },
        { label: 'Price', key: 'price' },
        { label: 'EMI', key: 'emi' },
        { label: 'Category', key: 'category' },
        { label: 'Mileage/Range', key: 'mileage' },
        { label: 'Safety Rating', key: 'safety' },
        { label: 'Transmission', key: 'transmission' },
        { label: 'Power', key: 'power' },
        { label: 'Engine', key: 'engine' },
        { label: 'Top Speed', key: 'topSpeed' },
        { label: 'Ground Clearance', key: 'groundClearance' },
        { label: 'Boot Space', key: 'bootSpace' },
    ];

    const [isExporting, setIsExporting] = React.useState(false);
    const scrollY = React.useRef(new Animated.Value(0)).current;

    React.useEffect(() => {
        navigation.setParams({ scrollY, handleExport: handleExportPDF } as any);
    }, [isExporting]);

    const handleExportPDF = async () => {
        setIsExporting(true);
        try {
            const htmlContent = `
                <html>
                <head>
                    <style>
                        body { font-family: 'Helvetica', 'Arial', sans-serif; padding: 20px; color: #1e293b; }
                        .header { text-align: center; margin-bottom: 30px; border-bottom: 2px solid #3b82f6; padding-bottom: 15px; }
                        .title { font-size: 28px; font-weight: bold; color: #3b82f6; margin-bottom: 5px; }
                        .subtitle { font-size: 14px; color: #64748b; }
                        .comparison-table { width: 100%; border-collapse: collapse; margin-top: 20px; table-layout: fixed; }
                        .comparison-table th, .comparison-table td { padding: 15px; border: 1px solid #e2e8f0; text-align: center; }
                        .label-cell { background-color: #f8fafc; font-weight: bold; text-align: left !important; width: 120px; }
                        .car-image { width: 100%; height: 120px; object-fit: cover; border-radius: 10px; margin-bottom: 10px; }
                        .car-brand { font-size: 12px; color: #64748b; text-transform: uppercase; font-weight: 600; }
                        .car-model { font-size: 16px; font-weight: bold; color: #1e293b; }
                        .value-text { font-size: 15px; color: #334155; }
                        .footer { margin-top: 40px; text-align: center; font-size: 12px; color: #94a3b8; border-top: 1px solid #e2e8f0; padding-top: 15px; }
                    </style>
                </head>
                <body>
                    <div class="header">
                        <div class="title">Vehicle Comparison Report</div>
                        <div class="subtitle">Generated by CarTrackApp on ${new Date().toLocaleDateString()}</div>
                    </div>
                    
                    <table class="comparison-table">
                        <thead>
                            <tr>
                                <th class="label-cell">Feature</th>
                                ${cars.map(car => `
                                    <th>
                                        <div class="car-brand">${car.brand}</div>
                                        <div class="car-model">${car.model}</div>
                                    </th>
                                `).join('')}
                            </tr>
                        </thead>
                        <tbody>
                                    ${comparisonData.map(item => `
                                <tr>
                                    <td class="label-cell">${item.label}</td>
                                    ${cars.map(car => `
                                        <td>
                                            <div class="value-text">
                                                ${item.key === 'price' ? car.price :
                    item.key === 'model' ? car.model :
                        item.key === 'year' ? car.year :
                            item.key === 'emi' ? car.emi :
                                item.key === 'category' ? (car.category || 'N/A') :
                                    (car.specs as any)[item.key]}
                                            </div>
                                        </td>
                                    `).join('')}
                                </tr>
                            `).join('')}
                        </tbody>
                    </table>
                    
                    <div class="footer">
                        This comparison report is for informational purposes only. Prices and specifications may vary.
                        <br/>&copy; 2024 CarTrackApp. All rights reserved.
                    </div>
                </body>
                </html>
            `;

            const { uri } = await Print.printToFileAsync({ html: htmlContent });

            if (await Sharing.isAvailableAsync()) {
                await Sharing.shareAsync(uri, {
                    mimeType: 'application/pdf',
                    dialogTitle: 'Download Comparison Report',
                    UTI: 'com.adobe.pdf',
                });
            } else {
                Alert.alert('Shared Failed', 'Sharing is not available on this device');
            }
        } catch (error) {
            console.error('PDF Export Error:', error);
            Alert.alert('Error', 'Failed to generate PDF report');
        } finally {
            setIsExporting(false);
        }
    };

    return (
        <View style={styles.container}>

            <Animated.ScrollView
                contentContainerStyle={styles.content}
                onScroll={Animated.event(
                    [{ nativeEvent: { contentOffset: { y: scrollY } } }],
                    { useNativeDriver: false }
                )}
                scrollEventThrottle={16}
            >
                <View style={styles.carsHeader}>
                    {cars.map((car) => (
                        <View key={car.id} style={styles.carColumn}>
                            <View style={styles.imageContainer}>
                                <Image source={{ uri: car.image }} style={styles.carPreviewImage} />
                            </View>
                            <Text style={styles.carBrand}>{car.brand}</Text>
                            <Text style={styles.carModel}>{car.model}</Text>
                        </View>
                    ))}
                </View>

                {comparisonData.map((item, index) => (
                    <View key={index} style={styles.comparisonRow}>
                        <Text style={styles.rowLabel}>{item.label}</Text>
                        <View style={styles.rowValues}>
                            {cars.map((car) => (
                                <View key={car.id} style={styles.valueColumn}>
                                    <Text style={styles.valueText}>
                                        {item.key === 'price' ? car.price :
                                            item.key === 'model' ? car.model :
                                                item.key === 'year' ? car.year :
                                                    item.key === 'emi' ? car.emi :
                                                        item.key === 'category' ? (car.category || 'N/A') :
                                                            (car.specs as any)[item.key]}
                                    </Text>
                                </View>
                            ))}
                        </View>
                    </View>
                ))}

                <Text style={styles.note}>
                    💡 Tap on any car to view detailed specifications, photos, and videos
                </Text>
            </Animated.ScrollView>
        </View>
    );
}

const styles = StyleSheet.create({
    container: { flex: 1, backgroundColor: COLORS.background },
    content: { paddingHorizontal: SIZES.padding, paddingBottom: 40 },
    header: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        paddingHorizontal: 20,
        paddingVertical: 15,
        backgroundColor: COLORS.white,
        borderBottomWidth: 1,
        borderBottomColor: '#F1F5F9',
    },
    headerTitle: {
        fontSize: 20,
        fontWeight: 'bold',
        color: COLORS.text,
    },
    exportButton: {
        backgroundColor: COLORS.primary + '15',
        paddingHorizontal: 15,
        paddingVertical: 8,
        borderRadius: 12,
        minWidth: 80,
    },
    exportContent: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        gap: 6,
    },
    exportText: {
        color: COLORS.primary,
        fontWeight: 'bold',
        fontSize: 14,
    },
    carsHeader: { flexDirection: 'row', marginBottom: 20, gap: 10 },
    carColumn: { flex: 1, alignItems: 'center', backgroundColor: COLORS.white, padding: 10, borderRadius: 15, ...SHADOWS.light },
    imageContainer: {
        width: '100%',
        height: 60,
        borderRadius: 10,
        overflow: 'hidden',
        marginBottom: 8,
        backgroundColor: '#F1F5F9',
    },
    carPreviewImage: {
        width: '100%',
        height: '100%',
        resizeMode: 'cover',
    },
    carBrand: { fontSize: 12, color: COLORS.textLight, fontWeight: '600' },
    carModel: { fontSize: 14, fontWeight: 'bold', color: COLORS.text, textAlign: 'center' },
    comparisonRow: { backgroundColor: COLORS.white, padding: 15, borderRadius: 15, marginBottom: 12, ...SHADOWS.light },
    rowLabel: { fontSize: SIZES.body1, fontWeight: 'bold', marginBottom: 10, color: COLORS.text },
    rowValues: { flexDirection: 'row', gap: 10 },
    valueColumn: { flex: 1, alignItems: 'center' },
    valueText: { fontSize: SIZES.body2, color: COLORS.textLight, textAlign: 'center' },
    note: { fontSize: SIZES.body3, color: COLORS.textLight, textAlign: 'center', marginTop: 20 },
});
